services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$DB_PASSWORD -Q \"SELECT 1\" -C -N || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
